### ISSUE TITLE
Implement 3d transforms

### ISSUE THREAD

**Issue by sixpi** [JuliaDSP/Wavelets.jl#17]
Hi,

Would it be hard to implement the 3d transforms? I am interested in doing 3d transforms.

Thanks

**Comment by holocronweaver** [comment]
:+1 I too am interested in 3D fast wavelet transforms.

**Comment by gummif** [comment]
I have implemented the transform, see https://github.com/JuliaDSP/Wavelets.jl/tree/v0.4.1
The version should be in METADATA.jl soon.
