### ISSUE TITLE
Extracting coefficients from filter

### ISSUE THREAD

**Issue by robertdj** [JuliaDSP/Wavelets.jl#24]
Hi,

Say I create a filter:

	julia> using Wavelets
	
	julia> F = waveletfilter("db2")
	Wavelets.WaveletTypes.OrthoFilter{Wavelets.WaveletTypes.PerBoundary}([0.4829629131445342,0.8365163037378079,0.22414386804201344,-0.12940952255126031],"db2")

How do I extract the vector of numbers from `F`?

I've been looking in the code, but I can't seem to figure this out.

Thanks,

Robert

**Comment by gummif** [comment]
Currently there is no function for that, but there probably should be. You can get the vector with `F.qmf` and in `Wavelets.Transforms` there are `makeqmf` and `makereverseqmf` function to make the qmf pairs. I will take a look at adding better functions for that.

**Comment by gummif** [comment]
See https://github.com/JuliaDSP/Wavelets.jl/commit/f68dc9c7c84c350b6ceb13bafc61e2fbdf0b826a

**Comment by robertdj** [comment]
Thanks! 

(Sorry about my long response time -- I've been away on paternity leave)
