### ISSUE TITLE
Fix v0.4 deprecation warnings

### ISSUE THREAD

**Issue by lostanlen** [JuliaDSP/Wavelets.jl#27]
I am running this package on Julia Version 0.4.1-pre+8.
When `using Wavelets`, four kinds of deprecation warning appear:
* `Base.String is deprecated, use AbstractString instead.`.
* `Base.FloatingPoint is deprecated, use AbstractFloat instead.`
* `Base.Nothing is deprecated, use Void instead.`
* `Union(args...) is deprecated, use Union{args...} instead.`

The warnings will become errors when v0.5 lands.
What is the compatibility policy for this package ?

**Comment by jfsantos** [comment]
The package has recently dropped support for 0.3, and official support is for 0.4. If these are warnings for 0.4, they should be fixed. @gummif has been working on fixing warnings recently so I guess he'll get to those soon, but feel free to submit a pull request if you want to help.

**Comment by lostanlen** [comment]
Thanks a lot @gummif ! :+1:

**Comment by lostanlen** [comment]
Updating the package to 0.5.0 did fix the warnings. Thank you both for your efficiency.
