### ISSUE TITLE
Example code not working :/

### ISSUE THREAD

**Issue by dioptre** [JuliaDSP/Wavelets.jl#28]
julia> y = dwt(x, wavelet(WT.cdf97, WT.Filter))
ERROR: MethodError: `wavelet` has no method matching wavelet(::Wavelets.WT.CDF{9,7}, ::Wavelets.WT.FilterTransform)
Closest candidates are:

**Comment by gummif** [comment]
I can't see that line in the example code but it looks like you have replaced `WT.Lifting` with `WT.Filter`. The `cdf` transforms are not defined yet for filters.

**Comment by dioptre** [comment]
Ok great thanks
