### ISSUE TITLE
Not working with Complex types

### ISSUE THREAD

**Issue by tknopp** [JuliaDSP/Wavelets.jl#29]
I have tried this package (much appreciated!) with an application to compressed sensing and it seems that currently the dwt and its inverse cannot be applied to complex numbers. Would be great if this could be solved by relaxing the type definitions.

**Comment by gummif** [comment]
I will see what I can do. Also, if you know of a simple test can for the unit tests that would be great.

**Comment by gummif** [comment]
This worked out more smoothly than I expected. v0.5.1 should be available soon from Pkg.

**Comment by tknopp** [comment]
Awesome, thanks!
