### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by tknopp** [JuliaDSP/Wavelets.jl#38]
Hi, I get various deprecation messanges under Julia 0.6. It seems they are resolved on Master. Could you make release @gummif?

Thanks,

Tobi

**Comment by gummif** [comment]
Sure, I will see if I can fix the travis script get the test to pass first, then I will make a release.

**Comment by tknopp** [comment]
Great thanks! Wonderfull package by the way. Am doing compressed sensing and use it for sparsity transformation.

**Comment by gummif** [comment]
Version 0.7 has been merged to METADATA.

**Comment by tknopp** [comment]
perfect, thanks!
