### ISSUE TITLE
Morlet wavelet

### ISSUE THREAD

**Issue by nie12** [JuliaDSP/Wavelets.jl#48]
Morlet wavelet analysis is needed in the analysis of waves. I hope it can be implemented.

**Comment by cdane** [comment]
There is a continuous wavelet transform with Morlet wavelets in this branch: eg. 
https://github.com/dsweber2/Wavelets.jl
e.g. xt = cwt(x, wavelet(WT.morl))

Conversation is here:
https://github.com/JuliaDSP/Wavelets.jl/pull/35

**Comment by Losses** [comment]
Still not merged after 2 years...? :anguished:

**Comment by gummif** [comment]
#35 has been merged.
