### ISSUE TITLE
tag version with SpecialFunctions 1

### ISSUE THREAD

**Issue by Datseris** [JuliaDSP/Wavelets.jl#67]
Hi,

please tag a release. current `master` branch has updated Project.toml.

**Comment by JeffFessler** [comment]
@gummif if you'd like some help with this type of housekeeping work I'm willing.  I could set up TagBot for example.

**Comment by gummif** [comment]
Sorry about that, there is now a PR open https://github.com/JuliaRegistries/General/pull/34433 that hopefully will not have any issues.

**Comment by gummif** [comment]
Version 0.9.3 has been released.
