### ISSUE TITLE
wplotim is destructive

### ISSUE THREAD

**Issue by Dejan-Ilic** [JuliaDSP/Wavelets.jl#71]
`wplotim` modifies the argument `x` it receives. I think either the function should be renamed to `wplotim!` 
or on line 83 of Plot.jl `xts = x` should be changed to `xts = copy(x)` (which seems the best option to me). Thanks for your time :)

**Comment by JeffFessler** [comment]
nice catch, thanks.
a workaround while waiting for a new version is `wplotim(copy(x))`

**Comment by gummif** [comment]
Good catch, a fix has been merged.
